apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "random-operator.fullname" . }}-job-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "delete", "update"]
