apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "random-operator.fullname" . }}-job-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "random-operator.fullname" . }}-job-role
subjects:
  - kind: ServiceAccount
    name: {{ include "random-operator.fullname" . }}-job-sa
    namespace: {{ .Release.Namespace }}
