apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "random-operator.fullname" . }}-cleanup-job
  annotations:
    helm.sh/hook: pre-delete
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["delete"]
